aws/aws-for-fluent-bit

integ/integ.sh
=> Integ Test: Run clean before the validation and use the `bash` shell

integ/integ.sh
=> Set LOG_GROUP_NAME for cloudwatch clean

README.md
- Add table of contents
- Add run on EC2 outside of containers tutorial
=> README improvements:

scripts/publish.sh
=> Fix verify_ssm function in publish script

entrypoint.sh
=> Bug fix: container exits with code 0 when sent a SIGTERM

buildspec.yml, buildspec_integ.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, scripts/publish.sh
=> Publish and Verify image using CI/CD Pipeline

buildspec.yml, buildspec_publish_ecr.yml, buildspec_publish_ssm.yml, buildspec_sync.yml, scripts/publish.sh
=> CI/CD Pipeline: Add sync mechanism and publish SSM parameters

buildspec_publish_ssm.yml
=> Fix typo in buildspec

buildspec_sync.yml, scripts/publish.sh
=> Update script file name and HongKong sync function

integ/resources/setup_test_environment.sh
=> remove echo in setup_test_environment.sh

integ/emf_logger/Dockerfile, integ/emf_logger/logscript.sh, integ/test_cloudwatch/docker-compose.test.yml, integ/test_cloudwatch/docker-compose.validate.yml, integ/test_cloudwatch/fluent-bit.conf, integ/validate_cloudwatch/validator.py
*Issue #, if available:* https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/27
Companion PR for https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/42
This one won't pass until https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/42 is released.
=> add end-to-end tests for EMF

scripts/publish.sh
=> Fix: if statement syntax for sync task image version

Dockerfile.plugins
=> Change base branch from 'master' to 'mainline' in all plugins

Dockerfile
Includes fix for https://github.com/fluent/fluent-bit/issues/2355
=> Build 1.5.0 release from 'aws-patch-1_5_0' branch

README.md
1. Updates README to add a new section- "Fluent Bit Examples".
2. Updates README to include Firehose plugin testing guideline.
=> Update README to include Fluent Bit examples section

buildspec.yml, buildspec_integ.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, integ/integ.sh, integ/resources/create_test_resources.sh, integ/resources/delete_test_resources.sh, integ/resources/setup_test_environment.sh, integ/validate_cloudwatch/validator.py, scripts/publish.sh
This reverts commit 28b23f67ab5191f842db14c5426e007323896d2f.
=> Revert "Support for ARM64 build"

Dockerfile.plugins, buildspec.yml, buildspec_integ.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, buildspec_publish_ssm.yml, buildspec_sync.yml, integ/s3/go.mod
Downgrade to go 1.14 due to the pipeline issue
=> Downgrade to go 1.14

Dockerfile.plugins, buildspec.yml, buildspec_integ.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, buildspec_publish_ssm.yml, buildspec_sync.yml, integ/s3/go.mod
Downgrade to go 1.13 due to the pipeline issue
=> Downgrade to go 1.13

scripts/publish.sh
=> Fix verify ssm: call docker login before pulling image

buildspec.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, buildspec_publish_ssm.yml, buildspec_sync.yml, scripts/get_latest_dockerhub_version.py, scripts/publish.sh
=> Fix CICD: get latest dockerhub version in a more robust way

buildspec_sync.yml
=> Go is not needed in sync task

integ/clean_cloudwatch/Dockerfile, integ/validate_cloudwatch/Dockerfile
=> install python from amazon linux

Dockerfile.plugins, integ/s3/Dockerfile
=> install golang from amazon linux

integ/clean_cloudwatch/Dockerfile, integ/validate_cloudwatch/Dockerfile
=> install pip from Amazon linux

scripts/publish.sh
=> Pipeline uses ${AWS_FOR_FLUENT_BIT_VERSION} and sync tasks use ${AWS_FOR_FLUENT_BIT_VERSION_DOCKERHUB}

buildspec.yml, buildspec_integ.yml
=> Authenticate to public ECR to prevent throttling

buildspec.yml, buildspec_integ.yml
=> Install latest AWS CLI 2.0 since CodeBuild isn't always up to date

buildspec.yml, buildspec_integ.yml
=> Add executable permissions to aws cli

buildspec.yml, buildspec_integ.yml
=> Let's see if this works

buildspec.yml, buildspec_integ.yml
=> Revert public ecr auth commits

integ/clean_cloudwatch/Dockerfile, integ/validate_cloudwatch/Dockerfile
=> Explicitly use pip3 and python3

scripts/publish.sh
=> Use correct version when pushing manifest list

buildspec_publish_public_ecr.yml, scripts/publish.sh
*Issue #123 , if available:*
Publish image onto ECR Public
=> Publish image to Public ECR

README.md
Add ECR Public update in README.md
=> Add ECR Public update in README.md

buildspec_sync.yml, scripts/publish.sh
Resolve the conflict naming in two arguments to make the sync task work
=> fix the conflicting argument issue

scripts/publish.sh
=> fix the mismatch of ECRPublic

scripts/publish.sh
=> fix login logic between private ECR and public ECR

buildspec_sync.yml, scripts/publish.sh
=> fix wrong logic of the if statement in sync task

buildspec_sync.yml, scripts/publish.sh
=> fix sync logic in us-west-2

scripts/publish.sh
=> Make ECR public login optional

buildspec_sync.yml
=> update AWS CLI version in US Gov

buildspec_sync.yml
=> Install AWS CLI 2 in US GOV

README.md
=> Add docs for aws-for-fluent-bit stable release

scripts/publish.sh
=> get the correct value of the image sha when verifying images in ECR

buildspec.yml, scripts/publish.sh
Stop accidental release in FluentBit pipeline 
=> Stop accidental release in FluentBit pipeline

buildspec.yml
=> chore: fix typo in buildspec

scripts/publish.sh
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
onboarding aws-for-fluent-bit image in CPT and MXP region
=> onboarding aws-for-fluent-bit image in CPT and MXP region

Dockerfile, ecs/amazon-es.conf, ecs/cloudwatch.conf, ecs/ecs-metadata.conf, ecs/filter-parser.conf, ecs/firehose.conf, ecs/input-forward.conf, ecs/kinesis.conf, ecs/s3.conf, ecs/service.conf
Add some common config files for Fluent Bit and provide additional options
=> Add sample configuration files

scripts/publish.sh
=> osaka region build

scripts/publish.sh
Fix wrong ssm parameter for stable image issue by adding a check for the value of existing ssm parameter.
=> fix wrong ssm parameter for stable image issue

README.md
=> update README for stable tag rule

CHANGELOG.md
=> Update changelog with 1.7.9 release note now that its available

CHANGELOG.md
Signed-off-by: Rayhan Hossain <hossain.rayhan@outlook.com>
Update wording in change-log
=> Update wording in change-log

buildspec.yml
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
remove the latest version match check
=> remove latest version match validation

buildspec.yml
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
=> revert remove latest version match validation commit

scripts/publish.sh
Signed-off-by: Zhonghui Hu <zh0512xx@gmail.com>
Update version check logic to let it check with all previous tags so that only new version can be released.
=> Update image version check logic in build stage

scripts/publish.sh
Signed-off-by: Zhonghui Hu <zh0512xx@gmail.com>
Add dockerhub login before version check.
=> add dockerhub login before version check

CHANGELOG.md, Dockerfile
Our last release didn't succeed so we don't need to update our image version
=> upgrade Fluent Bit version to fix S3 signv4 issue

.github/ISSUE_TEMPLATE/issue.md
=> Added issue template

Dockerfile, buildspec.yml, buildspec_integ.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, buildspec_publish_public_ecr.yml, buildspec_publish_ssm.yml
=> Fix upgrading issue with Go version 1.17

tests/.gitignore
=> Delete the gitignore file in tests folder

scripts/publish.sh
=> Fix the overwritten issue for latest tag in classic region

scripts/publish.sh
=> Logic typo in shell script

Makefile, integ/integ.sh, integ/test_cloudwatch/docker-compose.test.yml, integ/test_cloudwatch/fluent-bit.conf, integ/test_firehose/core-config/fluent-bit.conf, integ/test_firehose/docker-compose.core.test.yml, integ/test_kinesis/core-config/fluent-bit.conf, integ/test_kinesis/docker-compose.core.test.yml
=> Integration tests for the C kinesis_streams and kinesis_firehose plugins

CODEOWNERS
=> Add CODEOWNERS to repo

AWS_FLB_CHERRY_PICKS, Dockerfile
Signed-off-by: Matthew Fala <falamatt@amazon.com>
=> Resolve build version 2.21.5

README.md, troubleshooting/debugging.md, troubleshooting/tools/color-logger/Dockerfile, troubleshooting/tools/color-logger/README.md, troubleshooting/tools/color-logger/app.yaml, troubleshooting/tools/color-logger/fluent-bit.conf, troubleshooting/tools/color-logger/fluent-bit.yaml, troubleshooting/tools/color-logger/large.py, troubleshooting/tools/color-logger/log-tester.yaml, troubleshooting/tools/color-logger/main.py
=> Create debugging guide

CHANGELOG.md
=> Add multiline to changelog

CHANGELOG.md
=> Clarify multiline changelog

Dockerfile.debug, Makefile, troubleshooting/debugging.md
=> Added debug dockerfile and instructions for use

Makefile
=> Makefile: fix debug target

troubleshooting/debugging.md
=> debugging guide: add explanation of error messages

troubleshooting/tools/log4j-tcp-app/README.md, troubleshooting/tools/log4j-tcp-app/pom.xml, troubleshooting/tools/log4j-tcp-app/src/main/java/com/mycompany/app/App.java, troubleshooting/tools/log4j-tcp-app/src/main/java/com/mycompany/app/Dockerfile, troubleshooting/tools/log4j-tcp-app/src/main/java/com/mycompany/app/MultithreadApp.java, troubleshooting/tools/log4j-tcp-app/src/main/java/com/mycompany/app/run.txt, troubleshooting/tools/log4j-tcp-app/src/main/resources/log4j2.xml, troubleshooting/tools/log4j-tcp-app/src/test/java/com/mycompany/app/AppTest.java, troubleshooting/tools/log4j-tcp-app/src/test/log4j.properties
=> tools: add log4j example code

troubleshooting/debugging.md
=> Add overlimit warnings to troubleshooting guide

AWS_FLB_CHERRY_PICKS
=> Fix cherry pick commit ID for kube_token_ttl

load_tests/README.md
=> add README for ECS load testing framework

troubleshooting/debugging.md
=> fix broken link in debugging guide

buildspec_load_test.yml
=> fix EKS tests setup in ECS tests stage

CHANGELOG.md, Dockerfile
=> enable Apache Arrow support

README.md, use_cases/README.md, use_cases/k8s-metadata-customize-cw/README.md, use_cases/k8s-metadata-customize-cw/fluent-bit.yaml, use_cases/k8s-metadata-customize-tag/README.md, use_cases/k8s-metadata-customize-tag/fluent-bit.yaml
=> Start Use Case Guide with EKS templating examples

load_tests/README.md
=> add readme for EKS load test

troubleshooting/tools/log4j-tcp-app/pom.xml
I realized its very bad to have a sample test code that uses log4j 1.x even if its just sample test code... thanks dependabot
=> Update log4j 2 version in example app

troubleshooting/debugging.md
=> Debugging guide updates

use_cases/k8s-metadata-customize-cw/README.md
=> fix: Broken link in README.md

troubleshooting/debugging.md
=> Debugging guide: add note on core dumps in EKS

troubleshooting/debugging.md
=> Fix broken relative link in debugging guide

load_tests/setup_test_environment.sh
=> update load test app images to team account

Dockerfile, Dockerfile.debug
=> add required dependency in build time

README.md, use_cases/README.md, use_cases/init-process-for-fluent-bit/README.md
* add use case guide: multi-config support
=> add use case guide: multi-config support 

README.md
=> Advertize arm64 suppport clearly in README

AWS_FOR_FLUENT_BIT_VERSION
Signed-off-by: Matthew Fala <falamatt@amazon.com>
=> load_tests: test loadtests 2

AWS_FOR_FLUENT_BIT_VERSION
Signed-off-by: Matthew Fala <falamatt@amazon.com>
=> load_tests: test loadtests 3

README.md
=> Add compliance and patching note in README

troubleshooting/debugging.md
=> debugging guide: add tcp input invalid json message

troubleshooting/debugging.md
=> debugging guide: add log format section

Dockerfile.debug, troubleshooting/debugging.md, troubleshooting/tutorials/remote-core-dump/README.md, troubleshooting/tutorials/remote-core-dump/ecs-ec2-task-def.json, troubleshooting/tutorials/remote-core-dump/ecs-fargate-task-def.json
=> Debugging guide: add core dump tutorial

AWS_FLB_CHERRY_PICKS
=> cherry-pick: add windows user agent

troubleshooting/debugging.md
=> debugging guide: add note that overlimit also causes log loss

troubleshooting/debugging.md
=> debugging: add tail input rotation duplicate issue

README.md
=> Make it clear that stable is for the Fluent Bit code in image

scripts/build_plugins.sh
=> build_plugins.sh: handle opts being empty string

integ/test_init/README.md
=> integ: improve instructions for init integ test

troubleshooting/debugging.md
=> debugging: go vs c plugins

troubleshooting/debugging.md
=> debugging: improve log duplication section

troubleshooting/debugging.md
=> debugging: add SIGTERM and SIGSEGV section

troubleshooting/debugging.md
=> debugging: add FireLens tag and match pattern

troubleshooting/debugging.md
=> debugging: add log4j failure and failover

troubleshooting/debugging.md
=> debugging: add faq for high memory usage

linux.version, windows.versions
=> Bump both windows and linux to 2.29.0

integ/test_cloudwatch/fluent-bit.conf, integ/test_cloudwatch/windows-config/fluent-bit.conf, integ/test_firehose/core-config/fluent-bit.conf, integ/test_firehose/fluent-bit.conf, integ/test_firehose/windows-config/fluent-bit.conf, integ/test_firehose/windows-core-config/fluent-bit.conf, integ/test_kinesis/core-config/fluent-bit.conf, integ/test_kinesis/fluent-bit.conf, integ/test_kinesis/windows-config/fluent-bit.conf, integ/test_kinesis/windows-core-config/fluent-bit.conf
=> integ: set Retry_Limit 5 to reduce test randomness since default is 1

Dockerfile, configs/output-metrics-healthcheck.conf, configs/plugin-and-storage-metrics-to-cloudwatch.conf, configs/plugin-metrics-parser.conf, configs/plugin-metrics-to-cloudwatch.conf
=> built-in configs: add monitoring and healthcheck configs to image

troubleshooting/debugging.md
=> debugging: add unit test Dockerfile

troubleshooting/debugging.md
=> debugging: add steps to repro firelens locally

troubleshooting/debugging.md
**NOTE: This change should not be merged until this commit is released in our distro**: https://github.com/fluent/fluent-bit/pull/5428
=> Add batching and flush guidance to debugging guide

troubleshooting/tutorials/remote-core-dump/README.md
=> core dump tutorial: add sanity check idea for Fargate EFS setup

troubleshooting/debugging.md
=> debugging: note Grace setting in SIGTERM section

examples/fluent-bit/systems-manager-ec2/README.md, use_cases/README.md
=> use-case guide: add old ec2 ssm example

troubleshooting/debugging.md
=> debugging: add tail skipping file/line log loss section and log loss summary

troubleshooting/debugging.md, troubleshooting/tutorials/firelens-crash-repro-template/extra.conf, troubleshooting/tutorials/firelens-crash-repro-template/fluent-bit.conf, troubleshooting/tutorials/firelens-crash-repro-template/logfiles/command.txt, troubleshooting/tutorials/firelens-crash-repro-template/logfiles/example.log, troubleshooting/tutorials/firelens-crash-repro-template/logfiles/logfilescript.sh, troubleshooting/tutorials/firelens-crash-repro-template/run-fluent-bit.txt, troubleshooting/tutorials/firelens-crash-repro-template/stdout-logger/Dockerfile, troubleshooting/tutorials/firelens-crash-repro-template/stdout-logger/command.txt, troubleshooting/tutorials/firelens-crash-repro-template/stdout-logger/example.log, troubleshooting/tutorials/firelens-crash-repro-template/tcp-logger/command.txt, troubleshooting/tutorials/firelens-crash-repro-template/tcp-logger/example.log, troubleshooting/tutorials/firelens-crash-repro-template/tcp-logger/tcp-logger.sh
=> FireLens Customer Case Repro Template

troubleshooting/debugging.md
=> debugging: move what will my logs look like section to FAQ

AWS_FLB_CHERRY_PICKS, AWS_FOR_FLUENT_BIT_VERSION
=> Change version to 2.31.2-test-imdsv1-no-release to test load tests

AWS_FLB_CHERRY_PICKS
=> cherry-picks: add user agent type fix from #6584

windows.versions
=> Downgrade stable to 2.28.4 for windows customers as well

AWS_FLB_CHERRY_PICKS, AWS_FOR_FLUENT_BIT_VERSION, CHANGELOG.md, linux.version, windows.versions
=> Bump to 2.31.3

scripts/publish.sh
=> onboarding aws-for-fluent-bit image in CGK region

linux.version, scripts/common_windows.sh, scripts/get_latest_dockerhub_version.py, scripts/publish.sh
=> pipeline test: Add support for publishing a non-latest version

troubleshooting/debugging.md
=> debugging: faq: what version did I deploy?

integ/s3/go.mod
=> fix security warning and upgrade golang.org/x/net

integ/test_init/README.md
=> integ: init add link to file that must be changed

scripts/publish.sh
- fix spacing on line240
- check stable vs dockerhub to see if manifest "might" be missing
=> Add manifest if dockerhub not equal to stable

integ/test_init/integ_test/integ_test/integ_test_stack.py
=> add execution role to task definition

troubleshooting/debugging.md
=> debugging: faq: go <=> c migration

AWS_FLB_CHERRY_PICKS
=> cherry-picks: add new useful input debug messages

troubleshooting/debugging.md
=> debugging: add FAQ on how timestamps work in FLB

troubleshooting/debugging.md
=> debugging: add common network errors

troubleshooting/tutorials/remote-core-dump/README.md
=> core dump tutorial: add note on how to use and install debuginfo-install

troubleshooting/debugging.md
=> debugging: note that log deletion is needed to ensure tail performance

README.md
=> compliance: note/advertise we also use ECR AWS Inspector scan

Dockerfile.debug-base, Dockerfile.init, Dockerfile.plugins, troubleshooting/debugging.md
=> debugging: update the amazonlinux version from latest to 2

troubleshooting/debugging.md
=> debugging: Too Many Open Files error

AWS_FLB_CHERRY_PICKS, CHANGELOG.md
Supports: https://github.com/aws-samples/amazon-ecs-firelens-examples/pull/110
=> Add clear storage over limit message

integ/test_init/config_files_for_test/dummy-Input.conf, integ/test_init/config_files_for_test/dummy-input.conf
=> Change configuration file name from dummy-input.conf to dummy-input.conf.

integ/validate_cloudwatch/validator.py
=> integ: fix cloudwatch validator.py

troubleshooting/debugging.md
=> debugging: add table of contents for which version did I deploy

troubleshooting/debugging.md
=> debugging: add FAQ on stdout vs stderr

README.md
=> README: add consuming versions guidance

scripts/dockerfiles/Dockerfile.build-init, scripts/dockerfiles/Dockerfile.plugins, scripts/dockerfiles/Dockerfile.plugins-windows
=> add GOPROXY env when fails and retry

README.md, buildspec.yml, buildspec_publish_dockerhub.yml, buildspec_publish_ecr.yml, buildspec_publish_public_ecr.yml, scripts/publish.sh, troubleshooting/debugging.md
=> add debug image to main pipeline
