aws/aws-for-fluent-bit

integ/integ.sh

When running the CI/CD call test_cloudwatch before clean_cloudwatch.

Clean CloudWatch log group once the validation is done

---

examples/fluent-bit/systems-manager-ec2/ConfigureFluentBitEC2.yaml
examples/fluent-bit/systems-manager-ec2/README.md
examples/fluent-bit/systems-manager-ec2/plugins.conf
examples/fluent-bit/systems-manager-ec2/td-agent-bit.conf

Adding example on how to install Fluent Bit and the AWS output plugins on Amazon Linux 2 via AWS Systems Manager

Adding SSM Example

---

integ/integ.sh

Though the cloudwatch integ test passes successfully, it is throwing an exception- file not found. It should exit with code zero. 

Update Cloudwatch integ test exit logic

---

entrypoint.sh

The -c option for exec deletes the current env, this stops env vars from working. 

Bugfix: change entrypoint from 'exec -c' to 'exec'

---

buildspec_sync.yml
scripts/publish.sh

For the verification process of our sync task, we were reading the image version from AWS_FOR_FLUENT_BIT_VERSION file of our gitHub source. It was causing the sync task to fail. With this change, we will read our latest image version from DockerHub which will solve the above mentioned problem.

Read image version from DockerHub instead of GitHub source

---

entrypoint.sh

Fixes #41
Using tput for pretty colors and fancier formatting is great, but it causes errors in execution. Since this is meant to be a noninteractive container, seeing this in the startup logs is a red herring to people.

remove tput commands (and errors)

---

Dockerfile
Dockerfile.plugins

N/A
We used to release directly from the `mainline` branch of individual plugins. This PR changed it so that the plugins are built from a specific version tag. I've successfully tested the Docker build once with `docker build --no-cache -t aws-fluent-bit-plugins:latest -f Dockerfile.plugins .` before starting to run into all the `rsc.io` issues this morning.

Stop releasing from mainline

---

README.md

The current link to td-agent-bit installation instructions lands on a page that no longer exists, I've replaced it with an updated link to the supported platforms that leads to installation details/packages based on the specific operating system of interest:
Fix broken link: https://docs.fluentbit.io/manual/installation/td-agent-bit --> https://docs.fluentbit.io/manual/installation/supported-platforms

Fix broken link to td-agent-bit installation

---

Dockerfile.plugins

The documented behaviour in README for building with dev plugins wasn't actually working. This let's the builder specify a branch name for kinesis, firehose, and cloudwatch plugins, while also letting the default tags still work. 

Use PLUGIN_BRANCH variables in Dockerfile.plugins for dev builds.

---

buildspec.yml
buildspec_integ.yml
buildspec_publish_dockerhub.yml
buildspec_publish_ecr.yml
integ/integ.sh
integ/resources/create_test_resources.sh
integ/resources/delete_test_resources.sh
integ/resources/setup_test_environment.sh
integ/validate_cloudwatch/validator.py
scripts/publish.sh

Support for ARM64 build
https://github.com/aws/aws-for-fluent-bit/issues/44
- PR does not include the changes for sync task. I will publish a separate PR for that. 
- Pipeline stages have been modified to allow for parallel multi-arch image builds (x86-64 and ARM64).

Support for ARM64 build

---

buildspec_integ.yml
buildspec_publish_dockerhub.yml
buildspec_publish_ecr.yml
buildspec_publish_ssm.yml
buildspec_sync.yml
scripts/publish.sh

It turns out that the AWS CLI only uses regional STS endpoints if you set a env var: https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-sts_regional_endpoints.html

Force the use of STS regional endpoints

---

integ/integ.sh
integ/out/expected-metric-name
integ/s3-logger/Dockerfile
integ/s3-logger/logscript.sh
integ/s3/validate-and-clean.go
integ/test_kinesis/docker-compose.validate-and-clean-s3.yml
integ/test_s3/docker-compose.test.yml
integ/test_s3/docker-compose.validate-and-clean-s3.yml
integ/test_s3/docker-compose.validate-s3-multipart.yml
integ/test_s3/docker-compose.validate-s3-putobject.yml
integ/test_s3/fluent-bit.conf
tests/.gitignore

These can't be merged until out_s3 is released.

Add integration tests for out_s3

---

buildspec.yml
buildspec_integ.yml
buildspec_publish_dockerhub.yml
buildspec_publish_ecr.yml
integ/integ.sh
integ/resources/create_test_resources.sh
integ/resources/delete_test_resources.sh
integ/resources/setup_test_environment.sh
integ/validate_cloudwatch/validator.py
scripts/publish.sh

Enabling ECR Image scanning on the updated pipeline.
Every time an image is built and pushed to ECR we will scan and report vulnerabilities. If there are vulnerabilities, the pipeline will immediately fail.
- added ecr image scan verification on the updated pipeline for multi-arch build. 
Hence this PR has changes from https://github.com/aws/aws-for-fluent-bit/pull/73 and https://github.com/aws/aws-for-fluent-bit/pull/76
- pipeline will fail if scan returns vulnerabilities
For ease of review, here are the changes specific to image scan
- https://github.com/MeghnaPrabhu/aws-for-fluent-bit/blob/ecr-image-scan/scripts/publish.sh#L280
- https://github.com/MeghnaPrabhu/aws-for-fluent-bit/blob/ecr-image-scan/scripts/publish.sh#L581
- …

Ecr image scanning for CI/CD

---

Dockerfile.plugins
buildspec.yml
buildspec_integ.yml
buildspec_publish_dockerhub.yml
buildspec_publish_ecr.yml
buildspec_publish_ssm.yml
buildspec_sync.yml
integ/s3/go.mod

The latest version of go 1.12 was released `2020/02/12`.
This contribution updates all the places that list go `1.12` to go `1.15`. I'm not sure what testing should be done. Rather unfamiliar with this repo. Go 1.15 brings a handful of new features; the one I'm specifically looking for is the addition of `%w` to `fmt`.

Upgrade to go 1.15

---

buildspec_sync.yml

Gov Cloud Code Build lacks AWS CLI 2.0, so install it manually

---

Dockerfile
Dockerfile.plugins
integ/clean_cloudwatch/Dockerfile
integ/emf_logger/Dockerfile
integ/logger/Dockerfile
integ/s3-logger/Dockerfile
integ/s3/Dockerfile
integ/validate_cloudwatch/Dockerfile

Replace the source of container images with ECR gallery

---

Dockerfile

Recently Fluent Bit seeing issue for OpenSSL: https://github.com/fluent/fluent-bit/issues/2973
And after it fixed, the image could not work without openssl11-devel install into our docker env.
So need to upgrade it to openssl11-devel for the connection issue.

upgrade to openssl11-devel

---

Dockerfile

closes #17 
We don't assume customers update RPM packages inside the container.
Removing the cache directory makes the image ~200MB smaller.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
NA
Removes /var/cache/yum to make the container image smaller.

Remove /var/cache/yum to reduce the size of the container image

---

scripts/publish.sh

Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
By Adding these error handler, script will work for new region build in which region stable version maybe missing
Have tested in personal account and build succeed.
```
[Container] 2021/03/23 09:28:56 Phase complete: BUILD State: SUCCEEDED
995 | [Container] 2021/03/23 09:28:56 Phase context status code:  Message:
996 | [Container] 2021/03/23 09:28:56 Entering phase POST_BUILD
997 | [Container] 2021/03/23 09:28:56 Phase complete: POST_BUILD State: SUCCEEDED
998 | [Container] 2021/03/23 09:28:56 Phase context status code:  Message:
999 | [Container] 2021/03/23 09:28:56 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
1000 | [Container] 2021/03/23 09:28:56 Phase context status code:  Message:
```
By submitting this …

fix the stable tag creation for new region

---

scripts/publish.sh

Previous API had no access in our publish IAM role. Therefore, I switch it to another api which should work in our current ARN.

fix wrong api for getting ssm parameter

---

CHANGELOG.md

The announcement note for Fluent Bit 1.7.8 was just sent. Replace it with current link for Fluent Bit 1.7.8.

replace the release note link in CHANGELOG as it is available

---

scripts/publish.sh

Login before pulling image for docker-verify. This will help to avoid the following error we are getting from our pipeline.
`docker pull amazon/aws-for-fluent-bit:latest`
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Login before pulling image for docker-verify

---

buildspec_sync.yml
scripts/publish.sh

Our sync tasks fail in most of regions and this is because we added dockerhub login in our verification step. In this case, we should only call this function when we are in us-west-2.

log into dockerhub in sync tasks only when we are in us-west-2

---

Dockerfile

Build a custom upstream image for aws-for-fluent-bit 2.20.0 release. Here is the base branch for building the image: https://github.com/fluent/fluent-bit/compare/v1.8.7...zhonghui12:custom-1.8.7?expand=1. I checkout the branch from fluent bit tag v1.8.7 and add ssl solution & mbedtls downgrade on it.
`make release` succeeds on my end.
Note: all commits in the branch: https://github.com/zhonghui12/fluent-bit/commits/custom-1.8.7

Build a custom upstream image for aws-for-fluent-bit 2.20.0

---

load_tests/load_test.py

Based on what I've observed, we need to set more buffer for logs to be sent to the destination. Otherwise, we will see more log loss than it should be.

set more buffer for logs sent to corresponding destination

---

integ/resources/create_test_resources.sh
integ/resources/delete_test_resources.sh
integ/resources/setup_test_environment.sh

In all of our pipeline code, we use `arm64` for 64 bit arm, but in these scripts, we were using the output of `uname` which uses `aarch64`. This fix ensures we always  `arm64` everywhere. 

integ: fix arm64 build

---

Dockerfile
Dockerfile.debug

Version 1.9 now tracks master rather than a separate branch in fluent bit. Pull master branch.
Signed-off-by: Matthew Fala <falamatt@amazon.com>

Switch branch to master v2.24.0

---

Dockerfile.plugins
Makefile
buildspec_windows_plugins.yml
scripts/build_windows_plugins.sh
windows.versions

As part of Windows support to aws-for-fluent-bit, we would be building the plugins and the fluent-bit binaries using CodeBuild projects and then staging the artifacts in an S3 bucket. We would then build our container images with these artifacts as per the build version.
We also wanted to introduce a mechanism wherein we can patch an existing version of Windows image. So let's say, we have 2.26.1 is the current version and we want to patch it for some bug. The new workflow would allow this patching and ensure that all the artifacts for any given aws-for-fluent-bit version are consistent set.
In this PR, we have-
- Added Codebuild spec for building the artifacts
- Added Make file target to build the plugins
- Added bash script which invokes the docker command to build the artifacts
- …

added support for building Windows fluent-bit output plugins

---

Dockerfile.init
Makefile
init/fluent_bit_init_entrypoint.sh
init/fluent_bit_init_process.go
init/fluent_bit_init_process_test.go

Users can build the new image  `amazon/aws-for-fluent-bit-init:latest` and original image `amazon/aws-for-fluent-bit:latest` as the same time by using the command  `make release`
---
Code Style
* Change the original code style to use a consistent code style and naming style with the team
* Change code structure for modularization and code reuse
Unit Test
* Add code for unit test in `fluent_bit_init_process_test.go`
Dockerfile
* Merge two dockerfiles into `Dockerfile.init`
---
* Change `Makefile`
Change the `make release` command, add `docker build -t amazon/aws-for-fluent-bit-init:latest -f Dockerfile.init .` After executing the `make release` command, will also build the image `amazon/aws-for-fluent-bit-init:latest`
* Create `Dockerfile.init`
This Dockerfile will build the new image …

Init Process for AWS for Fluent Bit on ECS

---

buildspec.yml
buildspec_publish_dockerhub.yml
buildspec_publish_ecr.yml
buildspec_publish_public_ecr.yml
scripts/publish.sh

**Changes**
Modify the Pipeline and Sync stack, 9 images will be release as the same time after merge. Will skip release and verify the stable version of init image for temporary use.
e.g. latest version: 2.27.0, stable version 2.26.5, will release:
`aws-for-fluent-bit:amd64-2.27.0`
`aws-for-fluent-bit:arm64-2.27.0`
`aws-for-fluent-bit:2.27.0`
`aws-for-fluent-bit:latest`
`aws-for-fluent-bit:stable`
`aws-for-fluent-bit:init-amd64-2.27.0`
`aws-for-fluent-bit:init-arm64-2.27.0`
`aws-for-fluent-bit:init-2.27.0`
`aws-for-fluent-bit:init-latest`
**Important Node:**
This PR is for temporary use instead of https://github.com/aws/aws-for-fluent-bit/pull/389 because currently we don’t have any stable version for init image

Modify Pipeline to release init images WITHOUT (now) stable tag

---

troubleshooting/debugging.md

Changes to debuggin file to provide support for the imds with hop 1, previously as per doc, we need to modify instances for hop2 to get the credentials.
with hostNetwork, even with hop1, it can fetch the credentials.

Debugging guide: add IMDS note for k8s

---

init/fluent_bit_init_process.go

When init images are used, they are counted as both ECS and init usage

change FLB_AWS_USER_AGENT to ecs-init

---

Dockerfile.plugins
Dockerfile.windows
buildspec_windows_fluent-bit.yml
scripts/build_windows_fluent_bit.ps1
scripts/build_windows_image.ps1
scripts/build_windows_plugins.sh
scripts/entrypoint.ps1
windows.versions

This PR adds the complete support for building Windows images.
In order to build Windows images, we will be using a two step approach-
- Build all the fluent-bit artifacts as well as fluent-bit plugins. This can be done via the CodeBuild spec files included in the repository (`buildspec_windows_fluent-bit.yml` and `buildspec_windows_plugins.yml`)
- These CodeBuild projects would stage the following files in S3 which would be used in next step while building images-
- fluent-bit.zip
- plugins_windows.tar
- ecs.zip
- AWS_FOR_FLUENT_BIT_VERSION
- entrypoint.ps1
- Dockerfile.windows
**These are all the files which are used while building the images. Staging them in S3 would ensure that the image would be constant in a release month over month with the only change in base Windows image.**
- …

added support for building Windows images

---

Dockerfile.windows
scripts/build_windows_image.ps1

In Windows containers, by default, only Microsoft Root CA certificates are installed. 
Since Amazon Root CA certificates are not present, we would be installing them into the images from the cert source at 
https://www.amazontrust.com/
Addition of Amazon root CA certs for Windows images

windows: install Amazon root CA certificates during image build

---

Dockerfile.debug
troubleshooting/debugging.md

Updates the debugging guide to use version 2.28.
In addition to changing references from 2.21 to 2.28, this adds the `libyaml` library to the Dockerfile. The container will not start without it. I also added the `--error-limit=no` argument for valgrind to ensure that it will continue to log errors - even if there are a lot of them.

Updates debugging guide to use latest version

---

integ/resources/manage_test_resources.ps1
integ/run-integ.ps1
integ/test_cloudwatch/docker-compose.windows.test.yml
integ/test_cloudwatch/windows-config/fluent-bit.conf
integ/test_firehose/docker-compose.windows.test.yml
integ/test_firehose/windows-config/fluent-bit.conf
integ/test_firehose/windows-core-config/fluent-bit.conf
integ/test_kinesis/docker-compose.windows.test.yml
integ/test_kinesis/windows-config/fluent-bit.conf
integ/test_kinesis/windows-core-config/fluent-bit.conf
integ/test_s3/docker-compose.windows.test.yml
integ/test_s3/windows-config/fluent-bit.conf

This commits adds the required docker-compose projects, fluent-bit configurations, and the Powershell scripts needed to run the integration tests on Windows platform.
The design of the integration tests along with the constraints are detailed in the next section.
When we are using docker-compose to orchestrate our tests, we encounter a few limitations. Here, we detail the ways in which the same are mitigated.
- Fluent-bit for Windows would have to use the TCP sockets for receiving logs from other containers as Unix Sockets are not well supported. Basically, Fluent-bit would start first and listen on a port. Application containers would start after that and would use `fluentd` logging driver and connect to Fluent-bit `IP Address:Port`. 
- Therefore, in order to accommodate the same, we use …

Added support for running integration tests on Windows.

---

buildspec_windows_create_manifest.yml
integ/run-integ.ps1
scripts/build_windows_image.ps1

Windows images would have the following manifests-
- <AWS_FOR_FLB_VERSION>-windowsservercore
- windowsservercore-latest
- windowsservercore-stable
This change adds the buildspec which would be used in a CodeBuild project to generate the manifests for Windows images.
added the buildspec to generate manifests for Windows images
---

windows: added the buildspec for creating Windows image manifests

---

AWS_FOR_FLUENT_BIT_VERSION
load_tests/create_testing_resources/ecs/app.py

Added termination protection on instances protecting load tests from transient host kill errors

Bump test loadtests 4

---

scripts/publish_windows_images.ps1

For Windows, in order to publish the images, we would be creating EC2 instances for the underlying platform. We would then be using this script to pull the image from source and push the same to target registry/repository.
This script supports the following scenarios-
- Pull the image from regional ECR repository and push the image to another regional repository.
- Pull the image from regional ECR repository and push the image to public ECR repository.
- Pull the image from regional ECR repository and push the image to dockerhub repository.
- Pull the image from public ECR repository and push the image to regional ECR repository.
- Pull the image from public ECR repository and push the image to another public ECR repository.
- Pull the image from public ECR repository and push the image …

Windows: adds the publish image script for images

---

buildspec_windows_sync_images.yml
buildspec_windows_verify_images.yml
scripts/sync_windows_images.sh
scripts/verify_windows_images.sh

As part of our publishing workflow, we are pushing the images as well as the manifest into the target repository of the target registry. The next step would then verify if the images are infact present in the target repository.
Additionally, we have a sync task workflow, wherein we need to determine if we want to sync the images in regional ECR repository with the ones present in public ECR. Therefore, we compare the manifests of the same and then export a variable in CodeBuild project. This would be read by the subsequent stages in Step Function to determine if we do need to publish images into the regional ECR repository.
These scripts have been tested as part of an automated end to end workflow.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Windows: added the scripts for verifying images and determining if sync required

---

buildspec_windows_publish_ssm_params.yml
buildspec_windows_verify_ssm_parameters.yml
scripts/publish_windows_ssm_parameter.sh
scripts/verify_windows_ssm_parameters.sh

For AWS-for-fluent-bit images, we publish SSM Parameters in each regional store. The normal CodePipeline runs in the leader region of standard partition. As part of that workflow, we publish the SSM Parameters based on new images for each of the classic region in standard partition.
As part of sync-task workflow, we publish the SSM Parameter in each opt-in region as well as China and Gov cloud partition. This sync is based on the updated images in Public ECR repository.
As part of this change, we are adding the following-
- Script to publish and sync SSM parameter in each region
- Script to verify the SSM parameter in each region
- Buildspecs used by CodeBuild projects
These scripts have been tested as part of an automated end to end workflow.
By submitting this pull request, I confirm …

Windows: added the scripts for publishing and verifying SSM Parameters

---

scripts/build_windows_fluent_bit.ps1

There is a new CVE found in `openssl` due to which we are updating the openssl version used during Windows build to 3.0.7.
CVE description: https://www.openssl.org/blog/blog/2022/11/01/email-address-overflows/
upgrading openssl version to 3.0.7 for Windows build

windows: update the openssl version to 3.0.7

---

buildspec_windows_fluent-bit.yml
scripts/build_windows_fluent_bit.ps1
windows.versions

Presently, we have OpenSSL and FlexBison versions hardcoded in the build scripts itself. This means that changing the same requires a change to the build script. Additionally, the versions are then scattered across all the build files making it harder to understand.
Therefore, as part of this change, we are consolidating all in the master config file for Windows.
windows: consolidate all configurable versions in the config file

windows: consolidate all configurable versions in the config file

---

integ/run-integ.ps1

Due to less timeout, the integration tests for Kinesis Streams are failing. Therefore we are increasing the same.
windows: increase timeout for Kinesis and Firehose integ tests

windows: increase timeout for Kinesis and Firehose integ tests

---

scripts/get_latest_dockerhub_version.py

Presently, we are using get_latest_dockerhub_version.py script to fetch the latest version of image present on dockerhub. Since Windows tags start with number but later have letters, the scripts are failing. To mitigate the same, we add an extra condition wherein any tag which has - in them is ignored.
windows: ignore windows tags while fetching latest version

windows: ignore windows tags while fetching latest version

---

buildspec_sync.yml
buildspec_windows_publish_ssm_params.yml
buildspec_windows_verify_ssm_parameters.yml

Gov-Cloud only supports Python runtime version 3.7, 3.8, and 3.9. Therefore, we cannot use 3.x and would use 3.9.

updated python version to 3.9 for sync task

---

buildspec_sync.yml
buildspec_windows_publish_ssm_params.yml
buildspec_windows_verify_ssm_parameters.yml

Presently, all the Linux sync tasks are failing because of version 3.9 not available in classic regions. Therefore, downgrading it to 3.7.
updated python version to 3.7 for sync task

updated python version to 3.7 for sync task

---

scripts/common_windows.sh
scripts/get_latest_dockerhub_version.py
scripts/publish.sh

Presently, the Python script was used to fetch the latest version on Dockerhub irrespective of the platform. This couples the Linux releases to Windows releases. In order to decouple the same, we have introduced the first param as the platform name for which we need to fetch the latest version.
The workflow is-
- For Linux, consider the tags which do not have `windowsservercore` and `ltsc` in the tag name.
- For Windows, consider only the `windowsservercore` tags. The ones with `ltsc` are individual OS version tags and therefore can be skipped.
- Store the appropriate tag based on the platform.
windows: decouple Linux and Windows Dockerhub tags

windows: decouple Linux and Windows Dockerhub tags

---

troubleshooting/debugging.md

debugging: test: simple tcp logger script

---

scripts/entrypoint.ps1
troubleshooting/debugging.md

In order to obtain code dumps on Windows, we need to set a registry key which specifies the dump folder as well as the level of dump information. This is as per the Microsoft documentation- https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
We will be adding a parameter in the entrypoint.ps1 script which the customers can enable to generate the core dumps. Since these core dump files would be generated inside the container, we need to bind mount the location to the host to retrieve the same.
Created custom Windows images based on the new configuration and tested the same.
windows: add debugging option to the entrypoint script
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

windows: add debugging option to the entrypoint script

---

Makefile
scripts/entrypoint.ps1
windows.versions

Presently, the json is malformed in windows.versions file. The same has been rectified in this commit.
Also, added a makefile target "validate-version-file-format" which validates that the version file format is correct.
Lastly, there was an error in entrypoint script which was leading to failure for the build images. The same has been rectified as well.
---

windows: rectifying the malformed json and entrypoint script

---

AWS_FLB_CHERRY_PICKS
buildspec_load_test.yml

Resolve merge conflict in the retry limit PR.
The first s3 commit related to timestamps changes the name of a variable from create_time to first_log_time_stamp.
Then the second pr uses the create_time variable.
The new final commit is the same as the old final commit except create_time is changed to first_log_time_stamp

Bump 2.31.1 fix

---

load_tests/create_testing_resources/ecs/app.py

Disable imdsv1 in load test infrastructure
1. Start local pipeline
2. Wait for infra to be created
3. Obtain instance id in the AWS console.
4. Call the following aws-cli command: `aws ec2 modify-instance-metadata-options     --instance-id <my-instance-id>`
5. Check the results
1. The return value should have the InstanceMetadataOptions.HttpTokens fields set to "required"
```
{
"InstanceId": "<my-instance-id>",
"InstanceMetadataOptions": {
...
"HttpTokens": "required",
}
}
```
2. The loadtests still successfully run.
The return value should not have the InstanceMetadataOptions.HttpTokens fields set to "optional"
```
{
"InstanceId": "<my-instance-id>",
"InstanceMetadataOptions": {
...
"HttpTokens": "required",
}
}
```

Disable imdsv1 in loadtest infra

---

init/fluent_bit_init_process.go
init/fluent_bit_init_process_test.go
use_cases/init-process-for-fluent-bit/README.md

*Issue #, if available:* #538
*Description of changes:* Makes a task's AZ available as an environment variable.

init: Extracts Availability Zone from ECS Task Metadata.

---

CHANGELOG.md

Update 2.31.5's changelog to include a message about the new init feature: extract Availability Zone from ECS Task Metadata and inject into Fluent Bit container as `AWS_AVAILABILITY_ZONE` environment variable.

Update 2.31.5 changelog

---

scripts/publish.sh

- add sync_public_and_repo helper to simplify latest/init/stable tag syncing
- add support for syncing stable tag if not present in repo

Rework sync_latest_image to handle stable tag

---

buildspec_load_test.yml
buildspec_publish_public_ecr.yml
buildspec_sync.yml

Currently our 3 pipelines (load_test, public_ecr, sync) all install the aws cli v2. We were requested to move to a new CodeBuild project image, [STANDARD_5_0](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codebuild.LinuxBuildImage.html#static-standard_5_0) and noticed that AWS cli was already installed which caused a problem with our sync pipeline.
If we provide the `--update` field to the install it "should' handle updating if the AWS CLI is present or installing if not. The `--bin-dir` and `--install-dir` were slightly different across the pipelines which is not required. There were also additional shell commands which did not assist in the install/update of AWS CLI.
These changes were tested against STANDARD_2_0 (current) and STANDARD_5_0 CodeBuild …

Codebuild changes for aws cli present

---

CHANGELOG.md

This was correctly released: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/releases/tag/v1.9.2
See: https://github.com/aws/aws-for-fluent-bit/blob/v2.31.6/linux.version
And: https://github.com/aws/aws-for-fluent-bit/blob/v2.31.6/windows.versions
But I forgot to put it correctly in the changelog and release notes.

CHANGELOG: fix 1.9.2 cw go plugin was released in 2.31.6

---

buildspec_load_test.yml
buildspec_publish_public_ecr.yml
buildspec_sync.yml

- Opt to remove AWS CLI v1 (present in Codebuild V2 images), will skip without error if not found
- Install AWS CLI v2
- Print `which aws` and the version for debugging purposes
- Used uninstall guide for [Amazon Linux for CLI V1](https://docs.aws.amazon.com/cli/v1/userguide/install-linux-al2017.html#install-amazon-linux-pip-uninstall)

Stabilize our AWS CLI Install

---

scripts/publish.sh

- fix naming of imageTag --> tagCount for readability
- Provide helper method, sync_ssm, to handle checking/fallback logic with SSM Parameter Store with the following behavior
> If value is not present, we would receive error (set -e) and exit
> Instead we use `!` to check if the command failed and set a prepare boolean
> If the command succeeds we follow the normal logic to check if the request had invalid parameters
> If we should prepare the namespace or had invalid parameters we should attempt to put a variable in the namespace
> If we are an owner the request will succeed and the namespace is prepared
> If we are not an owner the request will fail with access denied and exit immediately
By submitting this pull request, I confirm that you can use, modify, …

Allow failover of SSM query when namespace has never been used

---

integ/validate_cloudwatch/validator.py

Presently, we are observing failures due to validator obtaining the logs from CloudWatch even though the same are present in CloudWatch. To account for flakiness, we are adding a universal retry mechanism in the script.
The following changes have been introduced in this PR-
- Added a retry mechanism to each validation test for max attempts of 20 and sleep time of 10 seconds.
- Changed the EMF start time to last 20 mins.
New output after the changes-
```
validate_cloudwatch % python3 validator.py
Tag for current run is: lkXFLbHQCD
RUNNING: CW Test 1: Basic Config
SUCCESS: CW Test 1: Basic Config
RUNNING: CW Test 2: log_key option
SUCCESS: CW Test 2: log_key option
RUNNING: CW Test 3: EMF metrics
SUCCESS: CW Test 3: EMF metrics
```
Earlier output before changes-
```
validate_cloudwatch % …
```

enhancements to the validator script to prevent flakiness

---

AWS_FLB_CHERRY_PICKS

CloudWatch Logs new options to support CWL api mocking.
While Mock API can support TLS, the Mock does not have valid CA Certs, and so TLS verify will fail.
Give an option to:
1. Opt out of TLS entirely (may use this only in rare cases)
2. Opt out of TLS verification (will use this commonly)
Here's the 1.9 code commit referenced:
- https://github.com/matthewfala/fluent-bit/commit/5d9692f00b5295728bf0340d332896a7cc450a7e
Here's the corresponding PR to master:
- https://github.com/fluent/fluent-bit/pull/7083

cherry-picks: support cloudwatch logs tls verify and port options

---

init/fluent_bit_init_process.go

[#537](https://github.com/aws/aws-for-fluent-bit/issues/537)
The init process should handle MULTILINE_PARSER in the same way as PARSER.
Currently, a validation error will occur in fluent bit.
https://github.com/fluent/fluent-bit/blob/v2.0.5/src/fluent-bit.c#L862

init: add multiline_parser
